// ****************** count_and_invert_booleans_safeInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _count_and_invert_booleans_safeInternal__h_INCLUDED
#define _count_and_invert_booleans_safeInternal__h_INCLUDED

#include "rtwtypes.h"
#include "coder_array.h"
#include "coder_bounded_array.h"
#include "count_and_invert_booleans_safe_types.h"
#include "count_and_invert_booleans_safe_data.h"
#include "count_and_invert_booleans_safe_initialize.h"
#include "count_and_invert_booleans_safe_terminate.h"
#include "count_and_invert_booleans_safe.h"

#define BoolCounterSafe_TYPES 1

#endif // _count_and_invert_booleans_safeInternal__h_INCLUDED