// ****************** count_and_invert_booleans_io_v2Internal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _count_and_invert_booleans_io_v2Internal__h_INCLUDED
#define _count_and_invert_booleans_io_v2Internal__h_INCLUDED

#include "rtwtypes.h"
#include "coder_array.h"
#include "coder_bounded_array.h"
#include "count_and_invert_booleans_io_v2_types.h"
#include "count_and_invert_booleans_io_v2_data.h"
#include "count_and_invert_booleans_io_v2_initialize.h"
#include "count_and_invert_booleans_io_v2_terminate.h"
#include "count_and_invert_booleans_io_v2.h"

#define BoolCounterIO_v2_TYPES 1

#endif // _count_and_invert_booleans_io_v2Internal__h_INCLUDED