
// ****************** FbBoolCounterSafe.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "FbBoolCounterSafe.h"

#ifdef EXT_MODE
#include "TcExtWork.h"
#endif

#include "count_and_invert_booleans_safe_initialize.h"
#include "count_and_invert_booleans_safe.h"
#include "count_and_invert_booleans_safe_terminate.h"

#include "ObjClassFactory.h"
using namespace TcMgSdk;

///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////
#if TC_BUILD<=4024
DEFINE_THIS_FILE()
#endif

///////////////////////////////////////////////////////////////////////////////
// CFbBoolCounterSafe specific globals
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbBoolCounterSafe static members
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbBoolCounterSafe implementation
///////////////////////////////////////////////////////////////////////////////
CFbBoolCounterSafe::CFbBoolCounterSafe()
{
	m_TraceLevelMax = tlInfo;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_SuppressExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_SuppressExceptions;


	
}

CFbBoolCounterSafe::~CFbBoolCounterSafe()
{

}

bool CFbBoolCounterSafe::FB_Main()
{

	HRESULT hr = S_OK;

	if (!m_Execute)
		return false;
	if (!m_Initialized)
		return false;

	if(SUCCEEDED(hr))
	{
		memset(&m_ActException, 0, sizeof(m_ActException));
		auto fpCtrl = FpControl(FpCtrlSection::Update);
		TcTry
		{
			if (hr == S_OK)
			{
				::count_and_invert_booleans_safe(*((coder::array<boolean_T,2>*)boolArray),maxOutputSize,&count,*((coder::array<boolean_T,2>*)inverseArray));
			}

		}
		TcExcept(ExceptionFilter(GetExceptionInformation()))
		{
			ExceptionHandler();
		}
		FpRestore(fpCtrl);
	}


	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbBoolCounterSafe::_FB_Main(ST_FB_BoolCounterSafe_FB_Main* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->FB_Main(  );
}

bool CFbBoolCounterSafe::FB_exit(bool bInCopyCode)
{

	HRESULT hr = S_OK;

	auto fpCtrl = FpControl(FpCtrlSection::Init);
	::count_and_invert_booleans_safe_terminate();
	if (((coder::array<boolean_T,2>*)boolArray)!=NULL)
	{
		delete ((coder::array<boolean_T,2>*)boolArray);
		boolArray = NULL;
	}
	if (((coder::array<boolean_T,2>*)inverseArray)!=NULL)
	{
		delete ((coder::array<boolean_T,2>*)inverseArray);
		inverseArray = NULL;
	}

	FpRestore(fpCtrl);


	SingleInstanceRelease();
	__super::Exit(bInCopyCode);

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbBoolCounterSafe::_FB_exit(ST_FB_BoolCounterSafe_FB_exit* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->FB_exit( ST_Param->bInCopyCode );
}

bool CFbBoolCounterSafe::FB_init(bool bInitRetains, bool bInCopyCode)
{

	HRESULT hr = S_OK;

	if(SUCCEEDED(hr))
	{
		m_pData = nullptr;
		hr = __super::Init(0,TC_BUILD_MIN,bInitRetains,bInCopyCode);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "Initialization of base class TcMatSim::GeneratedFb failed");
	}
	
	if(SUCCEEDED(hr))
	{
		boolArray = new coder::array<boolean_T,2>();
		memset(&(maxOutputSize),0,sizeof(maxOutputSize));
		memset(&(count),0,sizeof(count));
		inverseArray = new coder::array<boolean_T,2>();

	m_TraceLevelMax = tlInfo;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_SuppressExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_SuppressExceptions;


	}

	if (SUCCEEDED(hr))
	{
		hr = SingleInstanceLock(GUID_NULL);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "SingleInstanceLock() did not succeed");
	}
	
	if (SUCCEEDED(hr))
	{
		auto fpCtrl = FpControl(FpCtrlSection::Init);
		TcTry
		{
		::count_and_invert_booleans_safe_initialize();

		}
		TcExcept(ExceptionFilter(GetExceptionInformation(),FpCtrlSection::Init))
		{
			Log(TcTraceLevel::tlError, "Model initialization failed with an exception.");
			hr = E_FAIL;
		}
		FpRestore(fpCtrl);
	}
	
	if (SUCCEEDED(hr))
		hr = DataExchangeSetState(TCOM_STATE_OP,true);
	
	if (SUCCEEDED(hr))
	{
		m_Initialized = true;
		m_Execute = true;
	}
	else
	{
		m_Initialized = false;
		m_Execute = false;
	}

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbBoolCounterSafe::_FB_init(ST_FB_BoolCounterSafe_FB_init* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->FB_init( ST_Param->bInitRetains, ST_Param->bInCopyCode );
}

HRESULT CFbBoolCounterSafe::GetnHResult(HRESULT& nParam)
{
	nParam = m_HResult;
	return S_OK;
}

void CFbBoolCounterSafe::_GetnHResult(ST_GetSet_HRESULT* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GetnHResult( ST_Param->nParam );
}

HRESULT CFbBoolCounterSafe::GeteInitExceptionHandling(TcMgSdk::FpExcptCtrlSet& eParam)
{
	eParam = GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init);
	return S_OK;
}

void CFbBoolCounterSafe::_GeteInitExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GeteInitExceptionHandling( ST_Param->eParam );
}

HRESULT CFbBoolCounterSafe::SeteInitExceptionHandling(TcMgSdk::FpExcptCtrlSet eParam)
{
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = eParam;
	return S_OK;
}

void CFbBoolCounterSafe::_SeteInitExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->SeteInitExceptionHandling( ST_Param->eParam );
}

HRESULT CFbBoolCounterSafe::GeteUpdateExceptionHandling(TcMgSdk::FpExcptCtrlSet& eParam)
{
	eParam = GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update);
	return S_OK;
}

void CFbBoolCounterSafe::_GeteUpdateExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GeteUpdateExceptionHandling( ST_Param->eParam );
}

HRESULT CFbBoolCounterSafe::SeteUpdateExceptionHandling(TcMgSdk::FpExcptCtrlSet eParam)
{
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = eParam;
	return S_OK;
}

void CFbBoolCounterSafe::_SeteUpdateExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->SeteUpdateExceptionHandling( ST_Param->eParam );
}

HRESULT CFbBoolCounterSafe::GetnExceptionCnt(ULONGLONG& nParam)
{
	nParam = m_ExceptionCnt;
	return S_OK;
}

void CFbBoolCounterSafe::_GetnExceptionCnt(ST_GetSet_ULINT* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GetnExceptionCnt( ST_Param->nParam );
}

HRESULT CFbBoolCounterSafe::GetstActiveException(TcMgSdk::ExceptionInfo& stParam)
{
	stParam = m_ActException;
	return S_OK;
}

void CFbBoolCounterSafe::_GetstActiveException(ST_GetSet_ST_ExceptionInfo* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GetstActiveException( ST_Param->stParam );
}

HRESULT CFbBoolCounterSafe::GetbInitialized(bool& bParam)
{
	bParam = m_Initialized;
	return S_OK;
}

void CFbBoolCounterSafe::_GetbInitialized(ST_GetSet_BOOL* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GetbInitialized( ST_Param->bParam );
}

HRESULT CFbBoolCounterSafe::GetbExecute(bool& bParam)
{
	bParam = m_Execute;
	return S_OK;
}

void CFbBoolCounterSafe::_GetbExecute(ST_GetSet_BOOL* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->GetbExecute( ST_Param->bParam );
}

HRESULT CFbBoolCounterSafe::SetbExecute(bool bParam)
{
	m_Execute = bParam;
	return S_OK;
}

void CFbBoolCounterSafe::_SetbExecute(ST_GetSet_BOOL* ST_Param)
{
	((CFbBoolCounterSafe*)ST_Param->pInst)->SetbExecute( ST_Param->bParam );
}

HRESULT CFbBoolCounterSafe::put_boolArray(bool* data, LONG size1, LONG size2)
{
	HRESULT hr(S_OK);
	hr = TcMatSim::DataConversion::ToCoderArray(*((coder::array<boolean_T,2>*)boolArray),data,size1,size2);
	return hr;
}

void CFbBoolCounterSafe::_put_boolArray(ST_FB_BoolCounterSafe_put_boolArray* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->put_boolArray( ST_Param->data, ST_Param->size1, ST_Param->size2 );
}

HRESULT CFbBoolCounterSafe::get_boolArray(bool* data, LONG& size1, LONG& size2)
{
	HRESULT hr(S_OK);
	hr = TcMatSim::DataConversion::FromCoderArray(*((coder::array<boolean_T,2>*)boolArray),data,size1,size2);
	return hr;
}

void CFbBoolCounterSafe::_get_boolArray(ST_FB_BoolCounterSafe_get_boolArray* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->get_boolArray( ST_Param->data, ST_Param->size1, ST_Param->size2 );
}

HRESULT CFbBoolCounterSafe::get_inverseArray(bool* data, LONG& size1, LONG& size2)
{
	HRESULT hr(S_OK);
	hr = TcMatSim::DataConversion::FromCoderArray(*((coder::array<boolean_T,2>*)inverseArray),data,size1,size2);
	return hr;
}

void CFbBoolCounterSafe::_get_inverseArray(ST_FB_BoolCounterSafe_get_inverseArray* ST_Param)
{
	ST_Param->result = ((CFbBoolCounterSafe*)ST_Param->pInst)->get_inverseArray( ST_Param->data, ST_Param->size1, ST_Param->size2 );
}




BEGIN_FUNC_MAP_FB(CFbBoolCounterSafe)
	FUNC_ENTRY_LIB(VID_Tc3_BoolCounter, CID_FB_BOOLCOUNTERSAFE , "FB_BoolCounterSafe" "__main", CFbBoolCounterSafe::_FB_Main)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "FB_EXIT", "FB_BoolCounterSafe" "__FB_exit", CFbBoolCounterSafe::_FB_exit)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "FB_INIT", "FB_BoolCounterSafe" "__FB_init", CFbBoolCounterSafe::_FB_init)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETNHRESULT", "FB_BoolCounterSafe" "__GetnHResult", CFbBoolCounterSafe::_GetnHResult)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETEINITEXCEPTIONHANDLING", "FB_BoolCounterSafe" "__GeteInitExceptionHandling", CFbBoolCounterSafe::_GeteInitExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "SETEINITEXCEPTIONHANDLING", "FB_BoolCounterSafe" "__SeteInitExceptionHandling", CFbBoolCounterSafe::_SeteInitExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETEUPDATEEXCEPTIONHANDLING", "FB_BoolCounterSafe" "__GeteUpdateExceptionHandling", CFbBoolCounterSafe::_GeteUpdateExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "SETEUPDATEEXCEPTIONHANDLING", "FB_BoolCounterSafe" "__SeteUpdateExceptionHandling", CFbBoolCounterSafe::_SeteUpdateExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETNEXCEPTIONCNT", "FB_BoolCounterSafe" "__GetnExceptionCnt", CFbBoolCounterSafe::_GetnExceptionCnt)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETSTACTIVEEXCEPTION", "FB_BoolCounterSafe" "__GetstActiveException", CFbBoolCounterSafe::_GetstActiveException)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETBINITIALIZED", "FB_BoolCounterSafe" "__GetbInitialized", CFbBoolCounterSafe::_GetbInitialized)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GETBEXECUTE", "FB_BoolCounterSafe" "__GetbExecute", CFbBoolCounterSafe::_GetbExecute)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "SETBEXECUTE", "FB_BoolCounterSafe" "__SetbExecute", CFbBoolCounterSafe::_SetbExecute)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "PUT_BOOLARRAY", "FB_BoolCounterSafe" "__put_boolArray", CFbBoolCounterSafe::_put_boolArray)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GET_BOOLARRAY", "FB_BoolCounterSafe" "__get_boolArray", CFbBoolCounterSafe::_get_boolArray)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTERSAFE , "GET_INVERSEARRAY", "FB_BoolCounterSafe" "__get_inverseArray", CFbBoolCounterSafe::_get_inverseArray)
END_FUNC_MAP_FB()

DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbBoolCounterSafe)
{
	return CFbBoolCounterSafe::TcHandleFuncMap(mode, idx, idxcounter, pFncId, pipFnc, ppMethod, ppName, pSignature, pVersion);
}
