
// ****************** FbTcComBoolCounter.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "FbTcComBoolCounter.h"


#include "ObjClassFactory.h"
using namespace TcMgSdk;

///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////
#if TC_BUILD<=4024
DEFINE_THIS_FILE()
#endif

CFbTcComBoolCounter::CFbTcComBoolCounter()
{

}

CFbTcComBoolCounter::~CFbTcComBoolCounter()
{

}

bool CFbTcComBoolCounter::FB_init(bool bInitRetains, bool bInCopyCode, ST_FB_BoolCounter_TcCOM_InitStruct& stInit)
{

	HRESULT hr = S_OK;
	// Map Parameter
	memcpy(&(this->stInit),&stInit,sizeof(this->stInit));

	hr = __super::Init(0,TC_BUILD_MIN,bInitRetains,bInCopyCode);
	if (FAILED(hr))
		Log(TcTraceLevel::tlError, "Initialization of base class TcMatSim::GeneratedFbTcComWrapper failed");
		
	ITComObjectServerPtr psrv;
	TCOM_STATE eObjState = TCOM_STATE_INVALID;
	if (SUCCEEDED(hr))
		hr = GetObjectServer(&psrv);
	if(SUCCEEDED(hr))
	{
			if(stInit.nOid == OTCID_CreateNewId ||
			stInit.nOid == OTCID_FirstFreeId ||
			stInit.nOid == OTCID_LastFreeId)
		{
			hr = psrv->TcCreateInstance(GetVersionedCLSID(CID_BOOLCOUNTER,VID_Tc3_BoolCounter),IID_ITComObject,(PPVOID)&m_ipObj);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not create instance. hr = %X08",hr);
			
			if (SUCCEEDED(hr))
			{
				hr = m_ipObj->TcSetObjectId(stInit.nOid);
				if (FAILED(hr))
					Log(TcTraceLevel::tlError, "Could not set object ID. hr = %X08",hr);
			}
			if (SUCCEEDED(hr))
			{
				hr = strcmp(stInit.sObjName,"") == 0 ?  m_ipObj->TcSetObjectName(m_InstancePath) : m_ipObj->TcSetObjectName(stInit.sObjName);
				if (FAILED(hr))
					Log(TcTraceLevel::tlError, "Could not set object name. hr = %X08",hr);
			}
			
			if (SUCCEEDED(hr))
			{
				hr = m_ipObj->TcGetObjState(&eObjState);
				if (FAILED(hr))
					Log(TcTraceLevel::tlError, "Could not get object state. hr = %X08",hr);
				
				if (SUCCEEDED(hr) && (eObjState < TCOM_STATE_PREOP) && (TCOM_STATE_PREOP <= stInit.eObjState))
				{
					hr = m_ipObj->TcSetObjState(TCOM_STATE_PREOP, psrv, NULL);
					if (FAILED(hr))
					{
						Log(TcTraceLevel::tlError, "TcSetObjState to PreOp failed. hr = %X08",hr);
					}
					else
					{
						eObjState = TCOM_STATE_PREOP;
					}
				}
				if (stInit.eObjState > TCOM_STATE_PREOP)
				{
					if (SUCCEEDED(hr))
						hr = SetnTaskOid(stInit.nTaskOid);
					if (SUCCEEDED(hr))
						hr = SetnTaskSortOrder(stInit.nTaskSortOrder);
					if (SUCCEEDED(hr))
						hr = SeteTraceLevelMax(stInit.eTraceLevelMax);
					if (SUCCEEDED(hr))
						hr = SeteModuleCaller(stInit.eModuleCaller);
					if (SUCCEEDED(hr))
						hr = SeteCallerVerification(stInit.eCallerVerification);
					if (SUCCEEDED(hr))
						hr = SeteStepSizeAdaptation(stInit.eStepSizeAdaptation);
					if (SUCCEEDED(hr))
						hr = SeteExecutionSequence(stInit.eExecutionSequence);
					if (SUCCEEDED(hr))
						hr = SetbExecute(stInit.bExecute);
					if (SUCCEEDED(hr))
						hr = SeteAccessLockState(stInit.eAccessLockState);
					if (SUCCEEDED(hr))
						hr = SeteInitExceptionHandling(stInit.eInitExceptionHandling);
					if (SUCCEEDED(hr))
						hr = SeteUpdateExceptionHandling(stInit.eUpdateExceptionHandling);

				}
			}
		}
		else
		{
			/*** Query object interface ***/
			hr = psrv->TcQueryObjectInterface(stInit.nOid,IID_ITComObject,(PPVOID)&m_ipObj);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not query object interface \"ITComObject\". hr = %X08",hr);
			
			if (SUCCEEDED(hr))
				hr = GetObjState(eObjState);
			if (SUCCEEDED(hr) && (eObjState < TCOM_STATE_PREOP) && (TCOM_STATE_PREOP <= stInit.eObjState))
				hr = SetObjState(TCOM_STATE_PREOP);

		}
		/*** Query Interface ITcCyclic ***/
		if (SUCCEEDED(hr))
		{
			m_ipObj->TcQueryInterface(IID_ITcCyclic,(PPVOID)&m_ipCyclic);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not query object interface \"ITcCyclic\": hr = %08X",hr);
		}
		/*** Query Interface ITcPostCyclic ***/
		if (SUCCEEDED(hr))
		{
			m_ipObj->TcQueryInterface(IID_ITcPostCyclic,(PPVOID)&m_ipPostCyclic);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not query object interface \"ITcPostCyclic\": hr = %08X",hr);
		}
		/*** Query Interface ITcADI ***/
		if (SUCCEEDED(hr))
		{
			m_ipObj->TcQueryInterface(IID_ITcADI,(PPVOID)&m_ipADI);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not query object interface \"ITcADI\": hr = %08X",hr);
		}
		/*** Query Interface ITcBoolCounter ***/
		if (SUCCEEDED(hr))
		{
			m_ipObj->TcQueryInterface(IID_ITcBoolCounter,(PPVOID)&_ipBoolCounter);
			if (FAILED(hr))
				Log(TcTraceLevel::tlError, "Could not query object interface \"ITcBoolCounter\": hr = %08X",hr);
		}

	}
	if(SUCCEEDED(hr))
		hr = SetObjState(stInit.eObjState);

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbTcComBoolCounter::_FB_init(ST_FB_BoolCounter_TcCOM_InitStruct_FB_init* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->FB_init( ST_Param->bInitRetains, ST_Param->bInCopyCode, ST_Param->stInit );
}

bool CFbTcComBoolCounter::FB_afterinit()
{

	HRESULT hr = S_OK;

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbTcComBoolCounter::_FB_AfterInit(ST_FB_BoolCounter_TcCOM_InitStruct_FB_afterinit* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->FB_afterinit(  );
}

bool CFbTcComBoolCounter::Reinit(ST_FB_BoolCounter_TcCOM_InitStruct stReInit)
{

	HRESULT hr = S_OK;
	memcpy(&stInit,&stReInit,sizeof(stInit));
	if (SUCCEEDED(hr))
		hr = SetObjState(TCOM_STATE_PREOP);
					if (SUCCEEDED(hr))
						hr = SetnTaskOid(stInit.nTaskOid);
					if (SUCCEEDED(hr))
						hr = SetnTaskSortOrder(stInit.nTaskSortOrder);
					if (SUCCEEDED(hr))
						hr = SeteTraceLevelMax(stInit.eTraceLevelMax);
					if (SUCCEEDED(hr))
						hr = SeteModuleCaller(stInit.eModuleCaller);
					if (SUCCEEDED(hr))
						hr = SeteCallerVerification(stInit.eCallerVerification);
					if (SUCCEEDED(hr))
						hr = SeteStepSizeAdaptation(stInit.eStepSizeAdaptation);
					if (SUCCEEDED(hr))
						hr = SeteExecutionSequence(stInit.eExecutionSequence);
					if (SUCCEEDED(hr))
						hr = SetbExecute(stInit.bExecute);
					if (SUCCEEDED(hr))
						hr = SeteAccessLockState(stInit.eAccessLockState);
					if (SUCCEEDED(hr))
						hr = SeteInitExceptionHandling(stInit.eInitExceptionHandling);
					if (SUCCEEDED(hr))
						hr = SeteUpdateExceptionHandling(stInit.eUpdateExceptionHandling);

	if (SUCCEEDED(hr))
		hr = SetObjState(stInit.eObjState);
	m_HResult = hr;
return SUCCEEDED(hr);
}

void CFbTcComBoolCounter::_Reinit(ST_FB_BoolCounter_TcCOM_InitStruct_Reinit* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->Reinit( ST_Param->stReInit );
}

bool CFbTcComBoolCounter::FB_Main()
{

	HRESULT hr = S_OK;
	TCOM_STATE state;
	if (SUCCEEDED(hr))
		hr = GetObjState(state);
	if (SUCCEEDED(hr) && state != TCOM_STATE_OP)
		hr = LogOnce(ADS_E_INVALIDSTATE, TcTraceLevel::tlError, "TcCOM object is not in OP mode");
	CLSID clsid;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->GetClassId(clsid);
		if (FAILED(hr))
			LogOnce(hr, TcTraceLevel::tlError, "Unable to determine CLSID");
	}
	if (SUCCEEDED(hr))
	{
		const CLSID expectedClsid = GetVersionedCLSID(CID_BOOLCOUNTER,VID_Tc3_BoolCounter);
		if (memcmp(&clsid, &expectedClsid, sizeof(CLSID) != 0))
			hr = LogOnce(ADS_E_INVALIDCLSID,TcTraceLevel::tlError, "CLSID does not match");
	}


ModuleCaller eCaller;
if (SUCCEEDED(hr))
{
	PVOID pCaller = &eCaller;
	ULONG nCaller = sizeof(eCaller);
	hr = m_ipObj->TcGetObjPara(0x00000002,nCaller,pCaller);
	if (FAILED(hr)) 
		LogOnce(hr,TcTraceLevel::tlError, "TcGetObjPara of eModuleCaller (TcMgSdk.ModuleCaller) with PID 0x00000002 failed: hr = 0x%08X",hr);
}
if (SUCCEEDED(hr))
{
	if (eCaller == ModuleCaller::Module)
	{
		ITcRTimeTaskPtr ipTask;
		if (SUCCEEDED(hr))
			hr = GetCurrentTask(&ipTask);
		if (SUCCEEDED(hr) && m_ipPreInputCyclic)
			hr = m_ipPreInputCyclic->PreInputUpdate(ipTask,0,0);

		if (SUCCEEDED(hr) && m_ipCyclic)
			hr = m_ipCyclic->CycleUpdate(ipTask,0,0);
		if (SUCCEEDED(hr))
			hr = ReadOutputData(stOutports,0,"Outports");

		if (SUCCEEDED(hr) && m_ipPostCyclic)
			hr = m_ipPostCyclic->PostCyclicUpdate(ipTask,0,0);
	}
	else
	{
		hr = LogOnce(ADS_E_INVALIDPARM,TcTraceLevel::tlError, "Parameter \"ModuleCaller\" must be set to \"Module\"");
	}
}

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbTcComBoolCounter::_FB_Main(ST_FB_BoolCounter_TcCOM_InitStruct_FB_Main* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->FB_Main(  );
}

bool CFbTcComBoolCounter::FB_exit(bool bInCopyCode)
{

	HRESULT hr = S_OK;

	/* Check if FB is owner */
	if(stInit.nOid == OTCID_CreateNewId ||
	   stInit.nOid == OTCID_FirstFreeId ||
	   stInit.nOid == OTCID_LastFreeId)
	{
		hr = SetObjState(TCOM_STATE_INIT);
	}
	/*** Release Interface ITComObject ***/
	if (m_ipObj != NULL)
	{
		m_ipObj->TcRelease();
		m_ipObj = NULL;
	}
	/*** Release Interface ITcADI ***/
	if (m_ipADI != NULL)
	{
		m_ipADI->TcRelease();
		m_ipADI = NULL;
	}
	/*** Release Interface ITcPreInputCyclic ***/
	if (m_ipPreInputCyclic != NULL)
	{
		m_ipPreInputCyclic->TcRelease();
		m_ipPreInputCyclic = NULL;
	}
	/*** Release Interface ITcCyclic ***/
	if (m_ipCyclic != NULL)
	{
		m_ipCyclic->TcRelease();
		m_ipCyclic = NULL;
	}
	/*** Release Interface ITcPostCyclic ***/
	if (m_ipPostCyclic != NULL)
	{
		m_ipPostCyclic->TcRelease();
		m_ipPostCyclic = NULL;
	}
	/*** Release Interface ITcBoolCounter ***/
	if (_ipBoolCounter != NULL)
	{
		_ipBoolCounter->TcRelease();
		_ipBoolCounter = NULL;
	}

	__super::Exit(bInCopyCode);

	m_HResult = hr;
	return SUCCEEDED(hr);
}

void CFbTcComBoolCounter::_FB_exit(ST_FB_BoolCounter_TcCOM_InitStruct_FB_exit* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->FB_exit( ST_Param->bInCopyCode );
}

void CFbTcComBoolCounter::_GeteObjectState(ST_GetSet_TCOM_STATE* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetObjState( ST_Param->eParam );
}

void CFbTcComBoolCounter::_SeteObjectState(ST_GetSet_TCOM_STATE* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SetObjState( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GetnHResult(HRESULT& nParam)
{
	nParam = m_HResult;
	return S_OK;
}

void CFbTcComBoolCounter::_GetnHResult(ST_GetSet_HRESULT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnHResult( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetipTcComObject(ITComObject** ipParam)
{
	if (ipParam==nullptr)
		return E_INVALIDARG;
	*ipParam = m_ipObj;
	return S_OK;
}

void CFbTcComBoolCounter::_GetipTcComObject(ST_GetSet_ITComObject* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetipTcComObject( &ST_Param->ipParam );
}

HRESULT CFbTcComBoolCounter::GetipADI(ITcADI** ipParam)
{
	if (ipParam==nullptr)
		return E_INVALIDARG;
	*ipParam = m_ipADI;
	return S_OK;
}

void CFbTcComBoolCounter::_GetipADI(ST_GetSet_ITcADI* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetipADI( &ST_Param->ipParam );
}

HRESULT CFbTcComBoolCounter::put_boolArray(bool* data, LONG size1, LONG size2)
{
	if (_ipBoolCounter==NULL)
		return ADS_E_NOTINIT;
	return _ipBoolCounter->put_boolArray(data, size1, size2);

}

void CFbTcComBoolCounter::_put_boolArray(ST_FB_BoolCounter_TcCOM_InitStruct_put_boolArray* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->put_boolArray( ST_Param->data, ST_Param->size1, ST_Param->size2 );
}

HRESULT CFbTcComBoolCounter::get_boolArray(bool* data, LONG& size1, LONG& size2)
{
	if (_ipBoolCounter==NULL)
		return ADS_E_NOTINIT;
	return _ipBoolCounter->get_boolArray(data, size1, size2);

}

void CFbTcComBoolCounter::_get_boolArray(ST_FB_BoolCounter_TcCOM_InitStruct_get_boolArray* ST_Param)
{
	ST_Param->result = ((CFbTcComBoolCounter*)ST_Param->pInst)->get_boolArray( ST_Param->data, ST_Param->size1, ST_Param->size2 );
}

HRESULT CFbTcComBoolCounter::GetnTaskOid(OTCID& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x03002060,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nTaskOid (OTCID) with PID 0x03002060 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnTaskOid(ST_GetSet_OTCID* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnTaskOid( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::SetnTaskOid(OTCID nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x03002060,sizeof(nParam),&nParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of nTaskOid (OTCID) with PID 0x03002060 failed: hr = 0x%08X",hr);
	}
	if (SUCCEEDED(hr))
	{
		ULONG taskPrio;
		hr = GetTaskPriority(nParam, taskPrio);
		if (SUCCEEDED(hr))
			hr = m_ipObj->TcSetObjPara(0x03002070,sizeof(taskPrio),&taskPrio);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara with PID 0x03002070 failed: hr = 0x%08X",hr);
	}
	if (SUCCEEDED(hr))
	{
		ULONG taskCycleTimeNs;
		hr = GetTaskCycletimeNs(nParam, taskCycleTimeNs);
		if (SUCCEEDED(hr))
			hr = m_ipObj->TcSetObjPara(0x03002080,sizeof(taskCycleTimeNs),&taskCycleTimeNs);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara with PID 0x03002080 failed: hr = 0x%08X",hr);
	}
	if (SUCCEEDED(hr))
	{
		USHORT taskPort;
		hr = GetTaskPort(nParam, taskPort);
		if (SUCCEEDED(hr))
			hr = m_ipObj->TcSetObjPara(0x03002090,sizeof(taskPort),&taskPort);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara with PID 0x03002090 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SetnTaskOid(ST_GetSet_OTCID* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SetnTaskOid( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetnTaskPriority(ULONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x03002070,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nTaskPriority (ULONG) with PID 0x03002070 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnTaskPriority(ST_GetSet_UDINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnTaskPriority( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetnTaskCycleTimeNs(ULONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x03002080,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nTaskCycleTimeNs (ULONG) with PID 0x03002080 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnTaskCycleTimeNs(ST_GetSet_UDINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnTaskCycleTimeNs( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetnTaskPort(USHORT& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x03002090,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nTaskPort (USHORT) with PID 0x03002090 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnTaskPort(ST_GetSet_UINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnTaskPort( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetnTaskSortOrder(ULONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x030020B0,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nTaskSortOrder (ULONG) with PID 0x030020B0 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnTaskSortOrder(ST_GetSet_UDINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnTaskSortOrder( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::SetnTaskSortOrder(ULONG nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x030020B0,sizeof(nParam),&nParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of nTaskSortOrder (ULONG) with PID 0x030020B0 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SetnTaskSortOrder(ST_GetSet_UDINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SetnTaskSortOrder( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GeteTraceLevelMax(TcTraceLevel& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000001,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eTraceLevelMax (TcTraceLevel) with PID 0x00000001 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteTraceLevelMax(ST_GetSet_TcTraceLevel* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteTraceLevelMax( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteTraceLevelMax(TcTraceLevel eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000001,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eTraceLevelMax (TcTraceLevel) with PID 0x00000001 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteTraceLevelMax(ST_GetSet_TcTraceLevel* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteTraceLevelMax( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteModuleCaller(TcMgSdk::ModuleCaller& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000002,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eModuleCaller (TcMgSdk::ModuleCaller) with PID 0x00000002 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteModuleCaller(ST_GetSet_E_ModuleCaller* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteModuleCaller( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteModuleCaller(TcMgSdk::ModuleCaller eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000002,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eModuleCaller (TcMgSdk::ModuleCaller) with PID 0x00000002 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteModuleCaller(ST_GetSet_E_ModuleCaller* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteModuleCaller( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteCallerVerification(TcMgSdk::CallerVerification& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000003,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eCallerVerification (TcMgSdk::CallerVerification) with PID 0x00000003 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteCallerVerification(ST_GetSet_E_CallerVerification* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteCallerVerification( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteCallerVerification(TcMgSdk::CallerVerification eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000003,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eCallerVerification (TcMgSdk::CallerVerification) with PID 0x00000003 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteCallerVerification(ST_GetSet_E_CallerVerification* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteCallerVerification( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteStepSizeAdaptation(TcMgSdk::StepSizeAdaptation& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000004,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eStepSizeAdaptation (TcMgSdk::StepSizeAdaptation) with PID 0x00000004 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteStepSizeAdaptation(ST_GetSet_E_StepSizeAdaptation* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteStepSizeAdaptation( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteStepSizeAdaptation(TcMgSdk::StepSizeAdaptation eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000004,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eStepSizeAdaptation (TcMgSdk::StepSizeAdaptation) with PID 0x00000004 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteStepSizeAdaptation(ST_GetSet_E_StepSizeAdaptation* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteStepSizeAdaptation( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteExecutionSequence(TcMgSdk::ExecutionSequence1& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000005,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eExecutionSequence (TcMgSdk::ExecutionSequence1) with PID 0x00000005 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteExecutionSequence(ST_GetSet_E_ExecutionSequence1* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteExecutionSequence( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteExecutionSequence(TcMgSdk::ExecutionSequence1 eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000005,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eExecutionSequence (TcMgSdk::ExecutionSequence1) with PID 0x00000005 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteExecutionSequence(ST_GetSet_E_ExecutionSequence1* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteExecutionSequence( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GetbExecute(bool& bParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &bParam;
	ULONG nparam = sizeof(bParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000006,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of bExecute (bool) with PID 0x00000006 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetbExecute(ST_GetSet_BOOL* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetbExecute( ST_Param->bParam );
}

HRESULT CFbTcComBoolCounter::SetbExecute(bool bParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000006,sizeof(bParam),&bParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of bExecute (bool) with PID 0x00000006 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SetbExecute(ST_GetSet_BOOL* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SetbExecute( ST_Param->bParam );
}

HRESULT CFbTcComBoolCounter::GeteAccessLockState(TCOM_STATE& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000007,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eAccessLockState (TCOM_STATE) with PID 0x00000007 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteAccessLockState(ST_GetSet_TCOM_STATE* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteAccessLockState( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteAccessLockState(TCOM_STATE eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000007,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eAccessLockState (TCOM_STATE) with PID 0x00000007 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteAccessLockState(ST_GetSet_TCOM_STATE* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteAccessLockState( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteInitExceptionHandling(TcMgSdk::FpExcptCtrlSet& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000008,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eInitExceptionHandling (TcMgSdk::FpExcptCtrlSet) with PID 0x00000008 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteInitExceptionHandling(ST_GetSet_E_FpExcptCtrlSet* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteInitExceptionHandling( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteInitExceptionHandling(TcMgSdk::FpExcptCtrlSet eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000008,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eInitExceptionHandling (TcMgSdk::FpExcptCtrlSet) with PID 0x00000008 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteInitExceptionHandling(ST_GetSet_E_FpExcptCtrlSet* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteInitExceptionHandling( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GeteUpdateExceptionHandling(TcMgSdk::FpExcptCtrlSet& eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &eParam;
	ULONG nparam = sizeof(eParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000009,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of eUpdateExceptionHandling (TcMgSdk::FpExcptCtrlSet) with PID 0x00000009 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GeteUpdateExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GeteUpdateExceptionHandling( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::SeteUpdateExceptionHandling(TcMgSdk::FpExcptCtrlSet eParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x00000009,sizeof(eParam),&eParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of eUpdateExceptionHandling (TcMgSdk::FpExcptCtrlSet) with PID 0x00000009 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SeteUpdateExceptionHandling(ST_GetSet_E_FpExcptCtrlSetEx* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SeteUpdateExceptionHandling( ST_Param->eParam );
}

HRESULT CFbTcComBoolCounter::GetstModuleBuildInfo(TcMgSdk::ModuleBuildInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &stParam;
	ULONG nparam = sizeof(stParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000A,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of stModuleBuildInfo (TcMgSdk::ModuleBuildInfo) with PID 0x0000000A failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetstModuleBuildInfo(ST_GetSet_ST_ModuleBuildInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetstModuleBuildInfo( ST_Param->stParam );
}

HRESULT CFbTcComBoolCounter::GetbInitialized(bool& bParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &bParam;
	ULONG nparam = sizeof(bParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000B,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of bInitialized (bool) with PID 0x0000000B failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetbInitialized(ST_GetSet_BOOL* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetbInitialized( ST_Param->bParam );
}

HRESULT CFbTcComBoolCounter::GetnSkippedExecutionCount(ULONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000C,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nSkippedExecutionCount (ULONG) with PID 0x0000000C failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnSkippedExecutionCount(ST_GetSet_UDINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnSkippedExecutionCount( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetstLibraryInfo(TcMgSdk::LibraryInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &stParam;
	ULONG nparam = sizeof(stParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000D,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of stLibraryInfo (TcMgSdk::LibraryInfo) with PID 0x0000000D failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetstLibraryInfo(ST_GetSet_ST_LibraryInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetstLibraryInfo( ST_Param->stParam );
}

HRESULT CFbTcComBoolCounter::GetstModuleInfo(TcMgSdk::ModuleInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &stParam;
	ULONG nparam = sizeof(stParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000E,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of stModuleInfo (TcMgSdk::ModuleInfo) with PID 0x0000000E failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetstModuleInfo(ST_GetSet_ST_ModuleInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetstModuleInfo( ST_Param->stParam );
}

HRESULT CFbTcComBoolCounter::GetstModuleGeneratorInfo(TcMatSim_ModuleGeneratorInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &stParam;
	ULONG nparam = sizeof(stParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x0000000F,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of stModuleGeneratorInfo (TcMatSim_ModuleGeneratorInfo) with PID 0x0000000F failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetstModuleGeneratorInfo(ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetstModuleGeneratorInfo( ST_Param->stParam );
}

HRESULT CFbTcComBoolCounter::SetstModuleGeneratorInfo(TcMatSim_ModuleGeneratorInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	if (SUCCEEDED(hr))
	{
		hr = m_ipObj->TcSetObjPara(0x0000000F,sizeof(stParam),&stParam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcSetObjPara of stModuleGeneratorInfo (TcMatSim_ModuleGeneratorInfo) with PID 0x0000000F failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_SetstModuleGeneratorInfo(ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->SetstModuleGeneratorInfo( ST_Param->stParam );
}

HRESULT CFbTcComBoolCounter::GetnCycleCount(ULONGLONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000010,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nCycleCount (ULONGLONG) with PID 0x00000010 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnCycleCount(ST_GetSet_ULINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnCycleCount( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetnExceptionCount(ULONGLONG& nParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &nParam;
	ULONG nparam = sizeof(nParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000011,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of nExceptionCount (ULONGLONG) with PID 0x00000011 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetnExceptionCount(ST_GetSet_ULINT* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetnExceptionCount( ST_Param->nParam );
}

HRESULT CFbTcComBoolCounter::GetstExceptionInfo(TcMgSdk::ExceptionInfo& stParam)
{
	HRESULT hr =  m_ipObj ? S_OK : ADS_E_NOINTERFACE;
	PVOID pparam = &stParam;
	ULONG nparam = sizeof(stParam);
	if (SUCCEEDED(hr))
	{
		hr =  m_ipObj->TcGetObjPara(0x00000012,nparam,pparam);
		if (FAILED(hr))
			Log(TcTraceLevel::tlError, "TcGetObjPara of stExceptionInfo (TcMgSdk::ExceptionInfo) with PID 0x00000012 failed: hr = 0x%08X",hr);
	}
	return hr;

}

void CFbTcComBoolCounter::_GetstExceptionInfo(ST_GetSet_ST_ExceptionInfo* ST_Param)
{
	((CFbTcComBoolCounter*)ST_Param->pInst)->GetstExceptionInfo( ST_Param->stParam );
}



BEGIN_FUNC_MAP_FB(CFbTcComBoolCounter)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "FB_INIT", "FB_BoolCounter_TcCOM_InitStruct" "__FB_init", CFbTcComBoolCounter::_FB_init)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "FB_AFTERINIT", "FB_BoolCounter_TcCOM_InitStruct" "__FB_afterinit", CFbTcComBoolCounter::_FB_AfterInit)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "REINIT", "FB_BoolCounter_TcCOM_InitStruct" "__Reinit", CFbTcComBoolCounter::_Reinit)
	FUNC_ENTRY_LIB(VID_Tc3_BoolCounter, CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "FB_BoolCounter_TcCOM_InitStruct" "__main", CFbTcComBoolCounter::_FB_Main)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "FB_EXIT", "FB_BoolCounter_TcCOM_InitStruct" "__FB_exit", CFbTcComBoolCounter::_FB_exit)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEOBJECTSTATE", "FB_BoolCounter_TcCOM_InitStruct" "__GeteObjectState", CFbTcComBoolCounter::_GeteObjectState)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEOBJECTSTATE", "FB_BoolCounter_TcCOM_InitStruct" "__SeteObjectState", CFbTcComBoolCounter::_SeteObjectState)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNHRESULT", "FB_BoolCounter_TcCOM_InitStruct" "__GetnHResult", CFbTcComBoolCounter::_GetnHResult)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETIPTCCOMOBJECT", "FB_BoolCounter_TcCOM_InitStruct" "__GetipTcComObject", CFbTcComBoolCounter::_GetipTcComObject)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETIPADI", "FB_BoolCounter_TcCOM_InitStruct" "__GetipADI", CFbTcComBoolCounter::_GetipADI)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "PUT_BOOLARRAY", "FB_BoolCounter_TcCOM_InitStruct" "__put_boolArray", CFbTcComBoolCounter::_put_boolArray)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GET_BOOLARRAY", "FB_BoolCounter_TcCOM_InitStruct" "__get_boolArray", CFbTcComBoolCounter::_get_boolArray)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNTASKOID", "FB_BoolCounter_TcCOM_InitStruct" "__GetnTaskOid", CFbTcComBoolCounter::_GetnTaskOid)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETNTASKOID", "FB_BoolCounter_TcCOM_InitStruct" "__SetnTaskOid", CFbTcComBoolCounter::_SetnTaskOid)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNTASKPRIORITY", "FB_BoolCounter_TcCOM_InitStruct" "__GetnTaskPriority", CFbTcComBoolCounter::_GetnTaskPriority)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNTASKCYCLETIMENS", "FB_BoolCounter_TcCOM_InitStruct" "__GetnTaskCycleTimeNs", CFbTcComBoolCounter::_GetnTaskCycleTimeNs)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNTASKPORT", "FB_BoolCounter_TcCOM_InitStruct" "__GetnTaskPort", CFbTcComBoolCounter::_GetnTaskPort)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNTASKSORTORDER", "FB_BoolCounter_TcCOM_InitStruct" "__GetnTaskSortOrder", CFbTcComBoolCounter::_GetnTaskSortOrder)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETNTASKSORTORDER", "FB_BoolCounter_TcCOM_InitStruct" "__SetnTaskSortOrder", CFbTcComBoolCounter::_SetnTaskSortOrder)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETETRACELEVELMAX", "FB_BoolCounter_TcCOM_InitStruct" "__GeteTraceLevelMax", CFbTcComBoolCounter::_GeteTraceLevelMax)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETETRACELEVELMAX", "FB_BoolCounter_TcCOM_InitStruct" "__SeteTraceLevelMax", CFbTcComBoolCounter::_SeteTraceLevelMax)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEMODULECALLER", "FB_BoolCounter_TcCOM_InitStruct" "__GeteModuleCaller", CFbTcComBoolCounter::_GeteModuleCaller)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEMODULECALLER", "FB_BoolCounter_TcCOM_InitStruct" "__SeteModuleCaller", CFbTcComBoolCounter::_SeteModuleCaller)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETECALLERVERIFICATION", "FB_BoolCounter_TcCOM_InitStruct" "__GeteCallerVerification", CFbTcComBoolCounter::_GeteCallerVerification)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETECALLERVERIFICATION", "FB_BoolCounter_TcCOM_InitStruct" "__SeteCallerVerification", CFbTcComBoolCounter::_SeteCallerVerification)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETESTEPSIZEADAPTATION", "FB_BoolCounter_TcCOM_InitStruct" "__GeteStepSizeAdaptation", CFbTcComBoolCounter::_GeteStepSizeAdaptation)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETESTEPSIZEADAPTATION", "FB_BoolCounter_TcCOM_InitStruct" "__SeteStepSizeAdaptation", CFbTcComBoolCounter::_SeteStepSizeAdaptation)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEEXECUTIONSEQUENCE", "FB_BoolCounter_TcCOM_InitStruct" "__GeteExecutionSequence", CFbTcComBoolCounter::_GeteExecutionSequence)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEEXECUTIONSEQUENCE", "FB_BoolCounter_TcCOM_InitStruct" "__SeteExecutionSequence", CFbTcComBoolCounter::_SeteExecutionSequence)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETBEXECUTE", "FB_BoolCounter_TcCOM_InitStruct" "__GetbExecute", CFbTcComBoolCounter::_GetbExecute)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETBEXECUTE", "FB_BoolCounter_TcCOM_InitStruct" "__SetbExecute", CFbTcComBoolCounter::_SetbExecute)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEACCESSLOCKSTATE", "FB_BoolCounter_TcCOM_InitStruct" "__GeteAccessLockState", CFbTcComBoolCounter::_GeteAccessLockState)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEACCESSLOCKSTATE", "FB_BoolCounter_TcCOM_InitStruct" "__SeteAccessLockState", CFbTcComBoolCounter::_SeteAccessLockState)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEINITEXCEPTIONHANDLING", "FB_BoolCounter_TcCOM_InitStruct" "__GeteInitExceptionHandling", CFbTcComBoolCounter::_GeteInitExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEINITEXCEPTIONHANDLING", "FB_BoolCounter_TcCOM_InitStruct" "__SeteInitExceptionHandling", CFbTcComBoolCounter::_SeteInitExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETEUPDATEEXCEPTIONHANDLING", "FB_BoolCounter_TcCOM_InitStruct" "__GeteUpdateExceptionHandling", CFbTcComBoolCounter::_GeteUpdateExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETEUPDATEEXCEPTIONHANDLING", "FB_BoolCounter_TcCOM_InitStruct" "__SeteUpdateExceptionHandling", CFbTcComBoolCounter::_SeteUpdateExceptionHandling)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETSTMODULEBUILDINFO", "FB_BoolCounter_TcCOM_InitStruct" "__GetstModuleBuildInfo", CFbTcComBoolCounter::_GetstModuleBuildInfo)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETBINITIALIZED", "FB_BoolCounter_TcCOM_InitStruct" "__GetbInitialized", CFbTcComBoolCounter::_GetbInitialized)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNSKIPPEDEXECUTIONCOUNT", "FB_BoolCounter_TcCOM_InitStruct" "__GetnSkippedExecutionCount", CFbTcComBoolCounter::_GetnSkippedExecutionCount)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETSTLIBRARYINFO", "FB_BoolCounter_TcCOM_InitStruct" "__GetstLibraryInfo", CFbTcComBoolCounter::_GetstLibraryInfo)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETSTMODULEINFO", "FB_BoolCounter_TcCOM_InitStruct" "__GetstModuleInfo", CFbTcComBoolCounter::_GetstModuleInfo)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETSTMODULEGENERATORINFO", "FB_BoolCounter_TcCOM_InitStruct" "__GetstModuleGeneratorInfo", CFbTcComBoolCounter::_GetstModuleGeneratorInfo)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "SETSTMODULEGENERATORINFO", "FB_BoolCounter_TcCOM_InitStruct" "__SetstModuleGeneratorInfo", CFbTcComBoolCounter::_SetstModuleGeneratorInfo)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNCYCLECOUNT", "FB_BoolCounter_TcCOM_InitStruct" "__GetnCycleCount", CFbTcComBoolCounter::_GetnCycleCount)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETNEXCEPTIONCOUNT", "FB_BoolCounter_TcCOM_InitStruct" "__GetnExceptionCount", CFbTcComBoolCounter::_GetnExceptionCount)
	FUNC_METHOD_ENTRY_LIB(VID_Tc3_BoolCounter,CID_FB_BOOLCOUNTER_TCCOM_INITSTRUCT , "GETSTEXCEPTIONINFO", "FB_BoolCounter_TcCOM_InitStruct" "__GetstExceptionInfo", CFbTcComBoolCounter::_GetstExceptionInfo)
END_FUNC_MAP_FB()

DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbTcComBoolCounter)
{
	return CFbTcComBoolCounter::TcHandleFuncMap(mode, idx, idxcounter, pFncId, pipFnc, ppMethod, ppName, pSignature, pVersion);
}
