
// ****************** Tc3_BoolCounterCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _Tc3_BoolCounterCtrl__h_INCLUDED
#define _Tc3_BoolCounterCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CTc3_BoolCounterDrvName "Tc3_BoolCounter"

#include "Tc3_BoolCounterW32Resource.h"
#include "Tc3_BoolCounterW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "Tc3_BoolCounterClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CTc3_BoolCounterCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CTc3_BoolCounterCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CTc3_BoolCounterCtrl, CTc3_BoolCounterClassFactory>
{
public:
	CTc3_BoolCounterCtrl() : ITcOCFCtrlImpl<CTc3_BoolCounterCtrl, CTc3_BoolCounterClassFactory>(){}

	virtual ~CTc3_BoolCounterCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_Tc3_BoolCounterCtrl)
DECLARE_NOT_AGGREGATABLE(CTc3_BoolCounterCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CTc3_BoolCounterCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _Tc3_BoolCounterCtrl__h_INCLUDED