
// ****************** Tc3_BoolCounterClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "Tc3_BoolCounterClassFactory.h"
#include "Tc3_BoolCounterServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComcount_and_invert_booleans (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbcount_and_invert_booleans);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbTcComcount_and_invert_booleans);


#ifdef TcDrvUnversioned
IMPLEMENT_GETLIBRARYINFO_UNVERSIONED(Tc3_BoolCounter)
#else
IMPLEMENT_GETLIBRARYINFO(Tc3_BoolCounter)
#endif

DEFINE_REPOSITORY_DRIVER(CTc3_BoolCounterClassFactory, Tc3_BoolCounter_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CTc3_BoolCounterClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_Tc3_BoolCounter,CID_COUNT_AND_INVERT_BOOLEANS, SRVNAME_Tc3_BoolCounter "!CTcComcount_and_invert_booleans", Create_CTcComcount_and_invert_booleans)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CTc3_BoolCounterClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbcount_and_invert_booleans)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbTcComcount_and_invert_booleans)

END_FUNC_MAP()

CTc3_BoolCounterClassFactory::CTc3_BoolCounterClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_Tc3_BoolCounter)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_Tc3_BoolCounter));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Tc3_BoolCounter));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CTc3_BoolCounterClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			