// ****************** Tc3_BoolCounterDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _Tc3_BoolCounterDuts__h_INCLUDED
#define _Tc3_BoolCounterDuts__h_INCLUDED
#include "Tc3_BoolCounterServices.h"



#if count_and_invert_booleans_TYPES
#if !defined(_TC_TYPE_86D6B087_B335_805D_E79F_1F91489FA002_INCLUDED_)
#define _TC_TYPE_86D6B087_B335_805D_E79F_1F91489FA002_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_count_and_invert_booleans_FB_Main, *PST_FB_count_and_invert_booleans_FB_Main;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_count_and_invert_booleans_FB_Main, *PST_FB_count_and_invert_booleans_FB_Main;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_FB_Main = {0x86D6B087, 0xB335, 0x805D, {0xE7, 0x9F, 0x1F, 0x91, 0x48, 0x9F, 0xA0, 0x02}};
#endif // !defined(_TC_TYPE_86D6B087_B335_805D_E79F_1F91489FA002_INCLUDED_)

#if !defined(_TC_TYPE_1C7A1788_8781_7A20_1CAB_4CD802C5D5ED_INCLUDED_)
#define _TC_TYPE_1C7A1788_8781_7A20_1CAB_4CD802C5D5ED_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_count_and_invert_booleans_FB_exit, *PST_FB_count_and_invert_booleans_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_count_and_invert_booleans_FB_exit, *PST_FB_count_and_invert_booleans_FB_exit;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_FB_exit = {0x1C7A1788, 0x8781, 0x7A20, {0x1C, 0xAB, 0x4C, 0xD8, 0x02, 0xC5, 0xD5, 0xED}};
#endif // !defined(_TC_TYPE_1C7A1788_8781_7A20_1CAB_4CD802C5D5ED_INCLUDED_)

#if !defined(_TC_TYPE_25E43381_3A7E_1DBC_C4E8_A1C60712F79F_INCLUDED_)
#define _TC_TYPE_25E43381_3A7E_1DBC_C4E8_A1C60712F79F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1;
} ST_FB_count_and_invert_booleans_FB_init, *PST_FB_count_and_invert_booleans_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[5];
} ST_FB_count_and_invert_booleans_FB_init, *PST_FB_count_and_invert_booleans_FB_init;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_FB_init = {0x25E43381, 0x3A7E, 0x1DBC, {0xC4, 0xE8, 0xA1, 0xC6, 0x07, 0x12, 0xF7, 0x9F}};
#endif // !defined(_TC_TYPE_25E43381_3A7E_1DBC_C4E8_A1C60712F79F_INCLUDED_)

#if !defined(_TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_)
#define _TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#elif defined(_X64_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
	unsigned char reserved1[4];
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#endif
const GUID GUID_ST_GetSet_HRESULT = {0xA918DBD2, 0x68B1, 0x96AB, {0x50, 0x85, 0x00, 0x1E, 0x1E, 0x53, 0x7F, 0x56}};
#endif // !defined(_TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_)

#if !defined(_TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_)
#define _TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#endif
const GUID GUID_ST_GetSet_E_FpExcptCtrlSetEx = {0x5F7BDFDC, 0xE1B9, 0x123D, {0x8C, 0x10, 0x6D, 0x0E, 0x9A, 0xB2, 0xC2, 0x4F}};
#endif // !defined(_TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_)

#if !defined(_TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_)
#define _TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#endif
const GUID GUID_ST_GetSet_ULINT = {0x2EC54308, 0x2713, 0x3F94, {0xE2, 0x15, 0x86, 0xE3, 0x78, 0x35, 0x32, 0x9A}};
#endif // !defined(_TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_)

#if !defined(_TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_)
#define _TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#endif
const GUID GUID_ST_GetSet_ST_ExceptionInfo = {0x77EBBD72, 0x7A15, 0xF03E, {0x88, 0x00, 0xBE, 0x22, 0xFC, 0xBB, 0xBC, 0x3E}};
#endif // !defined(_TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_)

#if !defined(_TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_)
#define _TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[3];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#elif defined(_X64_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[7];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#endif
const GUID GUID_ST_GetSet_BOOL = {0xFABBB492, 0x0FDC, 0x5010, {0x36, 0x9A, 0xCF, 0x3F, 0x2D, 0x4F, 0xEB, 0xB9}};
#endif // !defined(_TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_)

#if !defined(_TC_TYPE_4C258632_3EEF_3D15_129B_6A4FACF5985E_INCLUDED_)
#define _TC_TYPE_4C258632_3EEF_3D15_129B_6A4FACF5985E_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_put_boolArray
{
	PVOID pInst;
	bool* data;
	LONG size1;
	LONG size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_put_boolArray, *PST_FB_count_and_invert_booleans_put_boolArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_put_boolArray
{
	PVOID pInst;
	bool* data;
	LONG size1;
	LONG size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_put_boolArray, *PST_FB_count_and_invert_booleans_put_boolArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_put_boolArray = {0x4C258632, 0x3EEF, 0x3D15, {0x12, 0x9B, 0x6A, 0x4F, 0xAC, 0xF5, 0x98, 0x5E}};
#endif // !defined(_TC_TYPE_4C258632_3EEF_3D15_129B_6A4FACF5985E_INCLUDED_)

#if !defined(_TC_TYPE_42A2567F_4720_8387_13AA_37D25BB64167_INCLUDED_)
#define _TC_TYPE_42A2567F_4720_8387_13AA_37D25BB64167_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_get_boolArray
{
	PVOID pInst;
	bool* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_get_boolArray, *PST_FB_count_and_invert_booleans_get_boolArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_get_boolArray
{
	PVOID pInst;
	bool* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_get_boolArray, *PST_FB_count_and_invert_booleans_get_boolArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_get_boolArray = {0x42A2567F, 0x4720, 0x8387, {0x13, 0xAA, 0x37, 0xD2, 0x5B, 0xB6, 0x41, 0x67}};
#endif // !defined(_TC_TYPE_42A2567F_4720_8387_13AA_37D25BB64167_INCLUDED_)

#if !defined(_TC_TYPE_39259772_AB9B_6884_6393_288600BE88F3_INCLUDED_)
#define _TC_TYPE_39259772_AB9B_6884_6393_288600BE88F3_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_put_inverseArray
{
	PVOID pInst;
	double* data;
	LONG size1;
	LONG size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_put_inverseArray, *PST_FB_count_and_invert_booleans_put_inverseArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_put_inverseArray
{
	PVOID pInst;
	double* data;
	LONG size1;
	LONG size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_put_inverseArray, *PST_FB_count_and_invert_booleans_put_inverseArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_put_inverseArray = {0x39259772, 0xAB9B, 0x6884, {0x63, 0x93, 0x28, 0x86, 0x00, 0xBE, 0x88, 0xF3}};
#endif // !defined(_TC_TYPE_39259772_AB9B_6884_6393_288600BE88F3_INCLUDED_)

#if !defined(_TC_TYPE_CC4781CD_315C_0917_D67B_36B99E463861_INCLUDED_)
#define _TC_TYPE_CC4781CD_315C_0917_D67B_36B99E463861_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_get_inverseArray
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_get_inverseArray, *PST_FB_count_and_invert_booleans_get_inverseArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_get_inverseArray
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_get_inverseArray, *PST_FB_count_and_invert_booleans_get_inverseArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_get_inverseArray = {0xCC4781CD, 0x315C, 0x0917, {0xD6, 0x7B, 0x36, 0xB9, 0x9E, 0x46, 0x38, 0x61}};
#endif // !defined(_TC_TYPE_CC4781CD_315C_0917_D67B_36B99E463861_INCLUDED_)

#if !defined(_TC_TYPE_DF5233B4_E230_EAF5_F5D1_84681E32CB0D_INCLUDED_)
#define _TC_TYPE_DF5233B4_E230_EAF5_F5D1_84681E32CB0D_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_get_inverseArray_
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_get_inverseArray_, *PST_FB_count_and_invert_booleans_get_inverseArray_;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_get_inverseArray_
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_get_inverseArray_, *PST_FB_count_and_invert_booleans_get_inverseArray_;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_get_inverseArray_ = {0xDF5233B4, 0xE230, 0xEAF5, {0xF5, 0xD1, 0x84, 0x68, 0x1E, 0x32, 0xCB, 0x0D}};
#endif // !defined(_TC_TYPE_DF5233B4_E230_EAF5_F5D1_84681E32CB0D_INCLUDED_)

#if !defined(_TC_TYPE_2DF33699_7535_05CD_C5A7_E42F401B78A3_INCLUDED_)
#define _TC_TYPE_2DF33699_7535_05CD_C5A7_E42F401B78A3_INCLUDED_
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct
{
	TCOM_STATE eObjState;
	STRING127 sObjName;
	OTCID nOid;
	OTCID nTaskOid;
	ULONG nTaskSortOrder;
	TcTraceLevel eTraceLevelMax;
	TcMgSdk::ModuleCaller eModuleCaller;
	TcMgSdk::CallerVerification eCallerVerification;
	TcMgSdk::StepSizeAdaptation eStepSizeAdaptation;
	TcMgSdk::ExecutionSequence1 eExecutionSequence;
	bool bExecute;
	unsigned char reserved1[3];
	TCOM_STATE eAccessLockState;
	TcMgSdk::FpExcptCtrlSet eInitExceptionHandling;
	TcMgSdk::FpExcptCtrlSet eUpdateExceptionHandling;
	unsigned char reserved2[2];
	TcMatSim_ModuleGeneratorInfo stModuleGeneratorInfo;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct;
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct = {0x2DF33699, 0x7535, 0x05CD, {0xC5, 0xA7, 0xE4, 0x2F, 0x40, 0x1B, 0x78, 0xA3}};
#endif // !defined(_TC_TYPE_2DF33699_7535_05CD_C5A7_E42F401B78A3_INCLUDED_)

#if !defined(_TC_TYPE_24CD7721_8D27_BD3B_DB0B_9A2FCE22D851_INCLUDED_)
#define _TC_TYPE_24CD7721_8D27_BD3B_DB0B_9A2FCE22D851_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_count_and_invert_booleans_TcCOM_InitStruct& stInit;
	bool result;
	unsigned char reserved2[3];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[6];
	ST_FB_count_and_invert_booleans_TcCOM_InitStruct& stInit;
	bool result;
	unsigned char reserved2[7];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_init = {0x24CD7721, 0x8D27, 0xBD3B, {0xDB, 0x0B, 0x9A, 0x2F, 0xCE, 0x22, 0xD8, 0x51}};
#endif // !defined(_TC_TYPE_24CD7721_8D27_BD3B_DB0B_9A2FCE22D851_INCLUDED_)

#if !defined(_TC_TYPE_9C5F27F1_6D56_A7E7_77F4_6069B283745B_INCLUDED_)
#define _TC_TYPE_9C5F27F1_6D56_A7E7_77F4_6069B283745B_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_afterinit = {0x9C5F27F1, 0x6D56, 0xA7E7, {0x77, 0xF4, 0x60, 0x69, 0xB2, 0x83, 0x74, 0x5B}};
#endif // !defined(_TC_TYPE_9C5F27F1_6D56_A7E7_77F4_6069B283745B_INCLUDED_)

#if !defined(_TC_TYPE_81E3E9F1_1A17_CE7F_D720_4B577A9DAF63_INCLUDED_)
#define _TC_TYPE_81E3E9F1_1A17_CE7F_D720_4B577A9DAF63_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit
{
	PVOID pInst;
	ST_FB_count_and_invert_booleans_TcCOM_InitStruct stReInit;
	bool result;
	unsigned char reserved1[3];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit
{
	PVOID pInst;
	ST_FB_count_and_invert_booleans_TcCOM_InitStruct stReInit;
	bool result;
	unsigned char reserved1[7];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_Reinit = {0x81E3E9F1, 0x1A17, 0xCE7F, {0xD7, 0x20, 0x4B, 0x57, 0x7A, 0x9D, 0xAF, 0x63}};
#endif // !defined(_TC_TYPE_81E3E9F1_1A17_CE7F_D720_4B577A9DAF63_INCLUDED_)

#if !defined(_TC_TYPE_C229F7D6_D89C_BA81_7452_B10539B58186_INCLUDED_)
#define _TC_TYPE_C229F7D6_D89C_BA81_7452_B10539B58186_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_Main = {0xC229F7D6, 0xD89C, 0xBA81, {0x74, 0x52, 0xB1, 0x05, 0x39, 0xB5, 0x81, 0x86}};
#endif // !defined(_TC_TYPE_C229F7D6_D89C_BA81_7452_B10539B58186_INCLUDED_)

#if !defined(_TC_TYPE_D9D21D07_59C9_BFA3_9076_C58738D973E3_INCLUDED_)
#define _TC_TYPE_D9D21D07_59C9_BFA3_9076_C58738D973E3_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_FB_exit = {0xD9D21D07, 0x59C9, 0xBFA3, {0x90, 0x76, 0xC5, 0x87, 0x38, 0xD9, 0x73, 0xE3}};
#endif // !defined(_TC_TYPE_D9D21D07_59C9_BFA3_9076_C58738D973E3_INCLUDED_)

#if !defined(_TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_)
#define _TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#elif defined(_X64_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
	unsigned char reserved1[4];
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#endif
const GUID GUID_ST_GetSet_TCOM_STATE = {0x2ED49A32, 0xE84B, 0xD386, {0xA7, 0xE6, 0x79, 0x77, 0xA4, 0x52, 0x93, 0x61}};
#endif // !defined(_TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_)

#if !defined(_TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_)
#define _TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_
typedef struct _ST_GetSet_ITComObject
{
	PVOID pInst;
	ITComObject* ipParam;
} ST_GetSet_ITComObject, *PST_GetSet_ITComObject;
const GUID GUID_ST_GetSet_ITComObject = {0x07FB5F29, 0x9630, 0x3C20, {0x61, 0x40, 0x7E, 0xD3, 0x26, 0x01, 0xF5, 0x21}};
#endif // !defined(_TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_)

#if !defined(_TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_)
#define _TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_
typedef struct _ST_GetSet_ITcADI
{
	PVOID pInst;
	ITcADI* ipParam;
} ST_GetSet_ITcADI, *PST_GetSet_ITcADI;
const GUID GUID_ST_GetSet_ITcADI = {0x858E8D33, 0x8412, 0x7D27, {0x0C, 0x7E, 0xD3, 0x9D, 0x04, 0x3A, 0xEF, 0x7C}};
#endif // !defined(_TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_)

#if !defined(_TC_TYPE_50741520_5EAF_5A55_5031_21D5F9A88729_INCLUDED_)
#define _TC_TYPE_50741520_5EAF_5A55_5031_21D5F9A88729_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray
{
	PVOID pInst;
	bool* data;
	LONG size1;
	LONG size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray
{
	PVOID pInst;
	bool* data;
	LONG size1;
	LONG size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_boolArray = {0x50741520, 0x5EAF, 0x5A55, {0x50, 0x31, 0x21, 0xD5, 0xF9, 0xA8, 0x87, 0x29}};
#endif // !defined(_TC_TYPE_50741520_5EAF_5A55_5031_21D5F9A88729_INCLUDED_)

#if !defined(_TC_TYPE_8BD29A33_80C8_85B4_2675_DCB13DC78E79_INCLUDED_)
#define _TC_TYPE_8BD29A33_80C8_85B4_2675_DCB13DC78E79_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray
{
	PVOID pInst;
	bool* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray
{
	PVOID pInst;
	bool* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_boolArray = {0x8BD29A33, 0x80C8, 0x85B4, {0x26, 0x75, 0xDC, 0xB1, 0x3D, 0xC7, 0x8E, 0x79}};
#endif // !defined(_TC_TYPE_8BD29A33_80C8_85B4_2675_DCB13DC78E79_INCLUDED_)

#if !defined(_TC_TYPE_3418213D_57DE_2B7C_45FF_426B94027DB4_INCLUDED_)
#define _TC_TYPE_3418213D_57DE_2B7C_45FF_426B94027DB4_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray
{
	PVOID pInst;
	double* data;
	LONG size1;
	LONG size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray
{
	PVOID pInst;
	double* data;
	LONG size1;
	LONG size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_put_inverseArray = {0x3418213D, 0x57DE, 0x2B7C, {0x45, 0xFF, 0x42, 0x6B, 0x94, 0x02, 0x7D, 0xB4}};
#endif // !defined(_TC_TYPE_3418213D_57DE_2B7C_45FF_426B94027DB4_INCLUDED_)

#if !defined(_TC_TYPE_78C83CA4_85EE_3D40_82F1_2533C1DC8A37_INCLUDED_)
#define _TC_TYPE_78C83CA4_85EE_3D40_82F1_2533C1DC8A37_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray = {0x78C83CA4, 0x85EE, 0x3D40, {0x82, 0xF1, 0x25, 0x33, 0xC1, 0xDC, 0x8A, 0x37}};
#endif // !defined(_TC_TYPE_78C83CA4_85EE_3D40_82F1_2533C1DC8A37_INCLUDED_)

#if !defined(_TC_TYPE_B23AFB3A_5D8C_B064_AEDD_5D1C95A406FE_INCLUDED_)
#define _TC_TYPE_B23AFB3A_5D8C_B064_AEDD_5D1C95A406FE_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_;
#elif defined(_X64_)
typedef struct _ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_
{
	PVOID pInst;
	double* data;
	LONG& size1;
	LONG& size2;
	HRESULT result;
	unsigned char reserved1[4];
} ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_, *PST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_;
#endif
const GUID GUID_ST_FB_count_and_invert_booleans_TcCOM_InitStruct_get_inverseArray_ = {0xB23AFB3A, 0x5D8C, 0xB064, {0xAE, 0xDD, 0x5D, 0x1C, 0x95, 0xA4, 0x06, 0xFE}};
#endif // !defined(_TC_TYPE_B23AFB3A_5D8C_B064_AEDD_5D1C95A406FE_INCLUDED_)

#if !defined(_TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_)
#define _TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#elif defined(_X64_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
	unsigned char reserved1[4];
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#endif
const GUID GUID_ST_GetSet_OTCID = {0xCC495849, 0x6A67, 0x6C41, {0xE5, 0x97, 0x58, 0xCD, 0xF0, 0x11, 0xD4, 0xF4}};
#endif // !defined(_TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_)

#if !defined(_TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_)
#define _TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#endif
const GUID GUID_ST_GetSet_UDINT = {0x82F235ED, 0x17E4, 0xB64A, {0xC3, 0x7C, 0x15, 0xDC, 0xC6, 0x0F, 0x86, 0x1B}};
#endif // !defined(_TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_)

#if !defined(_TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_)
#define _TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[2];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[6];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#endif
const GUID GUID_ST_GetSet_UINT = {0xBE5A5956, 0x3957, 0x8E47, {0xA6, 0x28, 0x49, 0xBF, 0x59, 0x73, 0x3E, 0x2A}};
#endif // !defined(_TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_)

#if !defined(_TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_)
#define _TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#elif defined(_X64_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
	unsigned char reserved1[4];
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#endif
const GUID GUID_ST_GetSet_TcTraceLevel = {0x07A6092B, 0xF404, 0xD8D8, {0x5A, 0x51, 0x19, 0x79, 0xED, 0x9F, 0x56, 0x09}};
#endif // !defined(_TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_)

#if !defined(_TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_)
#define _TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#endif
const GUID GUID_ST_GetSet_E_ModuleCaller = {0x449C630A, 0x94DE, 0xC008, {0x4C, 0xC4, 0x45, 0x14, 0xA2, 0xE9, 0x62, 0xD2}};
#endif // !defined(_TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_)

#if !defined(_TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_)
#define _TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#endif
const GUID GUID_ST_GetSet_E_CallerVerification = {0x5CC888CB, 0xF7E3, 0xF010, {0xA0, 0x55, 0x29, 0xF4, 0x0E, 0xCF, 0x09, 0xF8}};
#endif // !defined(_TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_)

#if !defined(_TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_)
#define _TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#endif
const GUID GUID_ST_GetSet_E_StepSizeAdaptation = {0x318995F4, 0xCE0A, 0xF9BF, {0x16, 0x20, 0x1E, 0x7E, 0xD3, 0xD6, 0x0E, 0x68}};
#endif // !defined(_TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_)

#if !defined(_TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_)
#define _TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#endif
const GUID GUID_ST_GetSet_E_ExecutionSequence1 = {0x8FD5CEAA, 0xA6E7, 0x56FF, {0xD4, 0xAA, 0x1D, 0x0B, 0x9D, 0xC7, 0x24, 0x59}};
#endif // !defined(_TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_)

#if !defined(_TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_)
#define _TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#endif
const GUID GUID_ST_GetSet_E_FpExcptCtrlSet = {0xEB954E8D, 0x311E, 0x2175, {0x43, 0x45, 0x0F, 0x03, 0x08, 0x23, 0x10, 0x0D}};
#endif // !defined(_TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_)

#if !defined(_TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_)
#define _TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#endif
const GUID GUID_ST_GetSet_ST_ModuleBuildInfo = {0x1818A80D, 0xC7C9, 0x0443, {0xCB, 0x25, 0xE5, 0x25, 0x12, 0x3E, 0xEC, 0x1F}};
#endif // !defined(_TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_)

#if !defined(_TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_)
#define _TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_
typedef struct _ST_GetSet_ST_LibraryInfo
{
	PVOID pInst;
	TcMgSdk::LibraryInfo stParam;
} ST_GetSet_ST_LibraryInfo, *PST_GetSet_ST_LibraryInfo;
const GUID GUID_ST_GetSet_ST_LibraryInfo = {0xABF10CB3, 0xB8CA, 0x886A, {0x77, 0x09, 0xA7, 0x22, 0x10, 0x06, 0xBE, 0x01}};
#endif // !defined(_TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_)

#if !defined(_TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_)
#define _TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_
typedef struct _ST_GetSet_ST_ModuleInfo
{
	PVOID pInst;
	TcMgSdk::ModuleInfo stParam;
} ST_GetSet_ST_ModuleInfo, *PST_GetSet_ST_ModuleInfo;
const GUID GUID_ST_GetSet_ST_ModuleInfo = {0x7C53BC2C, 0x3974, 0xD48A, {0x2D, 0x2E, 0x44, 0x8C, 0x7F, 0xC7, 0xF0, 0xD5}};
#endif // !defined(_TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_)

#if !defined(_TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_)
#define _TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_
typedef struct _ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo
{
	PVOID pInst;
	TcMatSim_ModuleGeneratorInfo stParam;
} ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo, *PST_GetSet_ST_TcMatSim_ModuleGeneratorInfo;
const GUID GUID_ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo = {0xCE84954A, 0xEAA1, 0x7210, {0x5F, 0x65, 0x6B, 0x38, 0xBB, 0x80, 0x22, 0x70}};
#endif // !defined(_TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_)

#endif // count_and_invert_booleans_TYPES


#endif // _Tc3_BoolCounterDuts__h_INCLUDED
