// ****************** Tc3_BoolCounterW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "Tc3_BoolCounterCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_Tc3_BoolCounterCtrl		=  {0x0D126023, 0xCDD5, 0x47A9, {0x99, 0x2D, 0x5C, 0xFE, 0x3C, 0x09, 0x60, 0x13}};
const   CLSID   LIBID_Tc3_BoolCounterW32Lib	=  {0x7020BD99, 0xC24B, 0x4186, {0x90, 0x97, 0x40, 0x6C, 0x9C, 0x9D, 0x7C, 0xBD}};
const   CLSID   CLSID_Tc3_BoolCounterCtrl   =  {0x14794DDA, 0x0F64, 0x42BB, {0xB6, 0xBA, 0xA9, 0x9B, 0x6C, 0x02, 0x7D, 0x42}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_Tc3_BoolCounterCtrl, CTc3_BoolCounterCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CTc3_BoolCounterCtrl>* pCTc3_BoolCounterCtrl = new CComObject<CTc3_BoolCounterCtrl>();
	if (pCTc3_BoolCounterCtrl == NULL) return E_POINTER;
	return pCTc3_BoolCounterCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
