// ****************** Tc3_BoolCounterInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _Tc3_BoolCounterInterfaces__h_INCLUDED
#define _Tc3_BoolCounterInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "Tc3_BoolCounterServices.h"

// interfaces provided by this driver


#if count_and_invert_booleans_TYPES
#if !defined(_TC_TYPE_5FBD272F_AB19_B253_1578_6419D5832637_INCLUDED_)
#define _TC_TYPE_5FBD272F_AB19_B253_1578_6419D5832637_INCLUDED_
struct __declspec(novtable) ITccount_and_invert_booleans : ITcUnknown 
{
	virtual HRESULT TCOMAPI count_and_invert_booleans(double& count) = 0;
	virtual HRESULT TCOMAPI put_boolArray(bool* data, LONG size1, LONG size2) = 0;
	virtual HRESULT TCOMAPI get_boolArray(bool* data, LONG& size1, LONG& size2) = 0;
	virtual HRESULT TCOMAPI put_inverseArray(double* data, LONG size1, LONG size2) = 0;
	virtual HRESULT TCOMAPI get_inverseArray(double* data, LONG& size1, LONG& size2) = 0;
	virtual HRESULT TCOMAPI get_inverseArray_(double* data, LONG& size1, LONG& size2) = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITccount_and_invert_booleans, IID_ITccount_and_invert_booleans);
const GUID GUID_ITccount_and_invert_booleans = {0x5FBD272F, 0xAB19, 0xB253, {0x15, 0x78, 0x64, 0x19, 0xD5, 0x83, 0x26, 0x37}};
#endif // !defined(_TC_TYPE_5FBD272F_AB19_B253_1578_6419D5832637_INCLUDED_)

#endif // count_and_invert_booleans_TYPES


#endif // _Tc3_BoolCounterInterfaces__h_INCLUDED
