
// ****************** Tc3_BoolCounterDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _Tc3_BoolCounterDrv__h_INCLUDED
#define _Tc3_BoolCounterDrv__h_INCLUDED

#include "TcPch.h"

#define Tc3_BoolCounterDRV_NAME			"Tc3_BoolCounter"
#define Tc3_BoolCounterDRV_Major			1
#define Tc3_BoolCounterDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CTc3_BoolCounterDrv

#include "ObjDriver.h"

class CTc3_BoolCounterDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl Tc3_BoolCounter_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( Tc3_BoolCounterDRV)
	VxD_Service( Tc3_BoolCounter_GetVersion		)
End_VxD_Service_Table


#endif // _Tc3_BoolCounterDrv__h_INCLUDED