// ****************** Tc3_BoolCounterServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.21.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.8.21.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _Tc3_BoolCounterServices__h_INCLUDED
#define _Tc3_BoolCounterServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedCFServiceProvider.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "Tc3_BoolCounterVersion.h"
#define SRVNAME_Tc3_BoolCounter "Tc3_BoolCounter"

// TcCOM-ClassID of CTcComcount_and_invert_booleans: {CD02428B-AF6F-AD0F-440B-E78CF4F3BE43}
const CTCID CID_COUNT_AND_INVERT_BOOLEANS = {0xCD02428B, 0xAF6F, 0xAD0F, {0x44, 0x0B, 0xE7, 0x8C, 0xF4, 0xF3, 0xBE, 0x43}};
// TcCOM-ClassID of CFbcount_and_invert_booleans: {EF97A945-56BC-B06D-AC38-6F511DA20F77}
const CTCID CID_FB_COUNT_AND_INVERT_BOOLEANS = {0xEF97A945, 0x56BC, 0xB06D, {0xAC, 0x38, 0x6F, 0x51, 0x1D, 0xA2, 0x0F, 0x77}};
// TcCOM-ClassID of CFbTcComcount_and_invert_booleans: {D43EFA18-56FE-D4D5-F0E9-628A3F9472AF}
const CTCID CID_FB_COUNT_AND_INVERT_BOOLEANS_TCCOM_INITSTRUCT = {0xD43EFA18, 0x56FE, 0xD4D5, {0xF0, 0xE9, 0x62, 0x8A, 0x3F, 0x94, 0x72, 0xAF}};


#ifndef Tc3_BoolCounter_IGNORE_SERVICES_TYPES
#if defined(count_and_invert_booleans_TYPES)
#else
	#define count_and_invert_booleans_TYPES 1
#endif


#if count_and_invert_booleans_TYPES
#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
const GUID GUID_STRING127 = {0x18071995, 0x0000, 0x0000, {0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x7F}};
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_B2BD15E5_07D2_554A_8AFB_AFD2E9C83B55_INCLUDED_)
#define _TC_TYPE_B2BD15E5_07D2_554A_8AFB_AFD2E9C83B55_INCLUDED_
typedef struct _count_and_invert_booleans_Outports
{
	double count;
} count_and_invert_booleans_Outports, *Pcount_and_invert_booleans_Outports;
const GUID GUID_count_and_invert_booleans_Outports = {0xB2BD15E5, 0x07D2, 0x554A, {0x8A, 0xFB, 0xAF, 0xD2, 0xE9, 0xC8, 0x3B, 0x55}};
#endif // !defined(_TC_TYPE_B2BD15E5_07D2_554A_8AFB_AFD2E9C83B55_INCLUDED_)

#if !defined(_TC_TYPE_BB79F3C5_FCA6_44F0_A017_6CA6C8C2A9DA_INCLUDED_)
#define _TC_TYPE_BB79F3C5_FCA6_44F0_A017_6CA6C8C2A9DA_INCLUDED_
typedef struct _TcMatSim_ModuleGeneratorInfo
{
	ULONG MatlabVersion[4];
	ULONG TE140xVersion[4];
} TcMatSim_ModuleGeneratorInfo, *PTcMatSim_ModuleGeneratorInfo;
const GUID GUID_TcMatSim_ModuleGeneratorInfo = {0xBB79F3C5, 0xFCA6, 0x44F0, {0xA0, 0x17, 0x6C, 0xA6, 0xC8, 0xC2, 0xA9, 0xDA}};
#endif // !defined(_TC_TYPE_BB79F3C5_FCA6_44F0_A017_6CA6C8C2A9DA_INCLUDED_)

#if !defined(_TC_TYPE_FD4C7972_05AE_2448_0104_7E043DE4AD81_INCLUDED_)
#define _TC_TYPE_FD4C7972_05AE_2448_0104_7E043DE4AD81_INCLUDED_
typedef struct _count_and_invert_booleans_Outports_T
{
	double count;
} count_and_invert_booleans_Outports_T, *Pcount_and_invert_booleans_Outports_T;
const GUID GUID_count_and_invert_booleans_Outports_T = {0xFD4C7972, 0x05AE, 0x2448, {0x01, 0x04, 0x7E, 0x04, 0x3D, 0xE4, 0xAD, 0x81}};
#endif // !defined(_TC_TYPE_FD4C7972_05AE_2448_0104_7E043DE4AD81_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
const GUID GUID_STRING255 = {0x18071995, 0x0000, 0x0000, {0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0xFF}};
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

#endif // count_and_invert_booleans_TYPES

#endif

TCOM_DECL_INTERFACE("5FBD272F-AB19-B253-1578-6419D5832637", ITccount_and_invert_booleans)



#endif // _Tc3_BoolCounterServices__h_INCLUDED
